  <a href="https://colab.research.google.com/github/marcpalo1999/MIA_sanidad/blob/main/2_0_Introduction_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
if not os.path.exists('/content/MIA_sanidad'):
    !git clone https://github.com/marcpalo1999/MIA_sanidad.git
os.chdir('/content/MIA_sanidad')
os.getcwd()


 # Introducción a Python



 En este notebook aprenderás conceptos básicos de Python:



 - Variables y asignación

 - Tipos de datos

 - Operaciones básicas

 - Strings y sus métodos

 - Listas

 - Condicionales y operadores lógicos

 - Bucles (`for`, `while`)

 - Funciones



 ---

 ## Capitulo 1. Variables y asignación



 En Python, una **variable** es un nombre que guarda un valor en memoria.

 Se asigna usando el signo `=`.

 Dentro de una variable se pueden guardar muchas cosas distintas (pero solo una cosa a la vez). Ejemplos de cosas que podemos guardar en una variable serian datos basicos, como enteros (int), decimales (float), texto (str), valores logicos/binarios (bool) o valores nulos (None)

In [ ]:
# Asignación de variables
edad_paciente = 45
peso_paciente = 70
edad_paciente


In [ ]:
nombre_medico = "Dr. García"
nombre_medico


In [ ]:
temperatura = 36.8
temperatura


In [ ]:
# Asignación múltiple
sistolica, diastolica, pulso = 120, 80, 75

# Impresión por pantalla usando f-strings
# Como veis los f-strings son muy útiles para combinar texto y variables en una misma línea
f"Presión: {sistolica}/{diastolica}, Pulso: {pulso}"


 ## Capitulo 2. Tipos de datos básicos



 Python tiene varios tipos de datos fundamentales:



 - **int** → números enteros como 1, 2, 100, -5 etc.

 - **float** → números decimales 3.14, 36.8, -2.5 etc.

 - **str** → texto o cadenas de caracteres como "Hola", "Dr. López", etc.

 - **bool** → valores lógicos (True o False). Analogamente son 1 y 0.

 - **None** → valor nulo, representa ausencia de valor

 Para saber que tipo de dato basico tengo dentro de mi variable (no el contenido, sinó el TIPO de dato), usamos la función type() nativa de python.

In [ ]:
edad = 30
type(edad)


In [ ]:
peso = 68.5
type(peso)


In [ ]:
diagnostico = "Hipertensión leve"
type(diagnostico)


In [ ]:
tiene_fiebre = True
type(tiene_fiebre)


 Podemos convertir nuestras variables a otros tipos con las funciones int(), str() y float() en algunos casos, si no es posible se nos devolverá un error al intentar ejecutar el codigo/comando

In [ ]:
# Conversión de tipos
edad_texto = "45"
edad_numero = int(edad_texto)
f"'{edad_texto}' convertido a entero: {edad_numero}"


In [ ]:
# Conversión de tipos
edad_texto = "cuarenta y cinco"
edad_numero = int(edad_texto)
f"'{edad_texto}' convertido a entero: {edad_numero}"


 ### Ejercicios capitulo 1 y 2: Variables y Tipos de Datos



 ### Ejercicio 1

 Crea las siguientes variables y muestra su contenido:



 1. Una variable llamada `nombre_paciente` con el valor "Ana López"

 2. Una variable llamada `edad` con el valor 32

 3. Una variable llamada `tiene_seguro` con el valor True



 Después, usa `type()` para mostrar el tipo de cada variable.

In [ ]:
# Respuesta ejercicio 1
# Crear variables
nombre_paciente = "Ana López"
edad = 32
tiene_seguro = True
# Mostrar los tipos
print(type(nombre_paciente))
print(type(edad))
print(type(tiene_seguro))


<class 'str'>
<class 'int'>
<class 'bool'>


 ### Ejercicio 2

 Completa las siguientes tareas:



 1. Crea una variable `temperatura_texto` con el valor de string "38.5"

 2. Convierte esta variable a número decimal y guárdala en `temperatura_numero`

 3. Crea una variable `paciente_id` con el valor integer 12345

 4. Convierte `paciente_id` a texto y guárdala en `paciente_id_texto`

 5. Usa un f-string para mostrar: "La temperatura del paciente (insertar ID paciente) es (insertar temperatura paciente) grados"

In [ ]:
# Respuesta ejercicio 2
# 1 Crea una variable temperatura_texto con el valor de string "38.5"
temperatura_texto = "38.5"
# 2 Convierte esta variable a número decimal y guárdala en temperatura_numero
temperatura_numero = float(temperatura_texto)
# 3 Crea una variable paciente_id con el valor integer 12345
paciente_id = 12345
# 4 Convierte paciente_id a texto y guárdala en paciente_id_texto
paciente_id_texto = str(paciente_id)
# 5 Usa un f-string para mostrar: "La temperatura del paciente (insertar ID paciente) es (insertar temperatura paciente) grados"
print(f"La temperatura del paciente {paciente_id_texto} es {temperatura_numero} grados")


La temperatura del paciente 12345 es 38.5 grados


 ## Capitulo 3. Operaciones básicas con numeros (int y float)



 Python soporta operaciones matemáticas y de comparación:

In [ ]:
# Operaciones aritméticas básicas
a = 15
b = 4


In [ ]:
a + b  # suma


In [ ]:
a - b  # resta


In [ ]:
a * b  # multiplicación


In [ ]:
a / b  # división


In [ ]:
a // b  # división entera


In [ ]:
a % b  # resto o módulo


In [ ]:
a ** 2  # potencia


In [ ]:
# Operadores de comparación
x = 10
y = 20


In [ ]:
x > y


In [ ]:
x < y


In [ ]:
x == y


NameError: name 'x' is not defined

In [ ]:
x != y


 ### Ejercicios capitulo 3: Operaciones Matemáticas Básicas



 ### Ejercicio 1



 Dadas las siguientes variables médicas:

 - `dosis_total = 500` (mg)

 - `numero_tomas = 4`



 Calcula y muestra:

 1. La dosis por toma (división)

 2. La dosis duplicada (multiplicación por 2)

 3. El resto de dividir la dosis total entre 3

In [ ]:
# Respuesta ejercicio 1

# Dadas las siguientes variables médicas:
dosis_total = 500
numero_tomas = 4

# Calcula y muestra:

# 1 La dosis por toma (división)
dosis_por_toma = dosis_total / numero_tomas
print(f"La dosis por toma es de {dosis_por_toma} mg")

# 2 La dosis duplicada (multiplicación por 2)
dosis_duplicada = 2 * dosis_total
print(f"La dosis duplicada es de {dosis_duplicada} mg")

# 3 El resto de dividir la dosis total entre 3
resto_dosis = dosis_total % 3
print(f"El resto de hacer 3 dosis es de {resto_dosis} mg")

La dosis por toma es de 125.0 mg
La dosis duplicada es de 1000 mg
El resto de hacer 3 dosis es de 2 mg


 ### Ejercicio 2



 Un paciente tiene los siguientes datos:

 - `peso_actual = 75` kg

 - `peso_ideal = 70` kg

 - `edad = 45` años

 - `edad_limite = 65` años



 Calcula y compara:

 1. La diferencia de peso

 2. Si el peso actual es mayor que el ideal

 3. Si la edad es menor que el límite

 4. Si la edad es exactamente 45

 5. Si la edad NO es 50

In [ ]:
# Respuesta ejercicio 2

# Crear variables
peso_actual = 75
peso_ideal = 70
edad = 45
edad_limite = 65

#Calcula y compara:

# 1.- La diferencia de peso
diferencia_peso = peso_actual - peso_ideal
print(f"La diferencia de peso entre el actual y el ideal es de {diferencia_peso} kg")

# 2.- Si el peso actual es mayor que el ideal
peso_actual_mayor = peso_actual > peso_ideal
print(f"¿Es el peso actual mayor que el peso ideal?: {peso_actual_mayor}")

# 3.-Si la edad es menor que el límite
edad_menor_que_limite = edad < edad_limite
print(f"¿Es la edad menor que el límite?: {edad_menor_que_limite}")

# 4.-Si la edad es exactamente 45
edad_exactamente_45 = edad == 45
print(f"¿Es la edad exactamente 45?: {edad_exactamente_45}")

# 5.- Si la edad NO es 50
edad_diferente_50 = edad != 50
print(f"¿Es la edad diferente de 50?: {edad_diferente_50}")


La diferencia de peso entre el actual y el ideal es de 5 kg
¿Es el peso actual mayor que el peso ideal?: True
¿Es la edad menor que el límite?: True
¿Es la edad exactamente 45?: True
¿Es la edad diferente de 50?: True


 ### Ejercicio 3



 Calculadora médica:

 1. Define `presion_sistolica = 140` y `presion_diastolica = 90`

 2. Calcula el ratio sistólica/diastólica usando división

 3. Calcula la presión del pulso (sistólica - diastólica)

 4. Eleva la presión sistólica al cuadrado

 5. Verifica si la presión sistólica es mayor o igual a 130

In [ ]:
# Respuesta ejercicio 3

# 1.-Define presion_sistolica = 140 y presion_diastolica = 90
presion_sistolica = 140
presion_diastolica = 90

# 2.-Calcula el ratio sistólica/diastólica usando división
ratio_sistolica_diastolica = presion_sistolica / presion_diastolica
print(f"El ratio sistólica/diástolica es {ratio_sistolica_diastolica}")

# 3.-Calcula la presión del pulso (sistólica - diastólica)
presion_pulso = presion_sistolica - presion_diastolica
print(f"La presión del pulso es {presion_pulso}")

# 4.-Eleva la presión sistólica al cuadrado
cuadrado_sistolica = presion_sistolica ** 2
print(f"El cuadrado de la presión sistólica es {cuadrado_sistolica}")

# 5.-Verifica si la presión sistólica es mayor o igual a 130
sistolica_mayor_igual_130 = presion_sistolica >= 130
print(f"Es la presión sistólica mayor o igual que 130?: {sistolica_mayor_igual_130}")

El ratio sistólica/diástolica es 1.5555555555555556
La presión del pulso es 50
El cuadrado de la presión sistólica es 19600
Es la presión sistólica mayor o igual que 130?: True


 ## Capitulo 4. Strings (Cadenas de texto)



 Los strings son secuencias de caracteres (comunmente conocido como texto). Se pueden definir con comillas simples o dobles, da lo mismo.
 Podemos acceder directamente a cada uno de los caracteres del string usando el metodo de indices de python, que tiene notación [].



 RECORDATORIO: Python es un lenguaje de programación basado en indice 0. Que significa eso? Que la primera posición de cualquier indice usado en python es 0, la segunda es 1 etc.

In [ ]:
medicamento = "Paracetamol"
medicamento


In [ ]:
# Métodos útiles de strings
medicamento.upper()  # convertir a mayúsculas


In [ ]:
medicamento.lower()  # convertir a minúsculas


In [ ]:
medicamento.replace('Paracetamol', 'Ibuprofeno')  # reemplazar texto


In [ ]:
# Acceso a caracteres
medicamento[0]  # primer carácter


In [ ]:
medicamento[-1]  # último carácter


In [ ]:
medicamento[2:5]  # substring del índice 2 al 4


In [ ]:
# Métodos adicionales útiles de strings
texto_con_espacios = "  Medicina Interna  "
texto_con_espacios.strip()  # eliminar espacios al principio y final


El metodo "in" comprueba si una secuencia de texto definida por nosotros, en este caso "hipertensión", esta de alguna manera encabida dentro de una variable. Si efectivamente está encabida, el metodo in nos devolvera verdadero o True, y si no es así nos devolvera Falso o False.

In [ ]:
# Verificar si un texto contiene otro texto
diagnostico = "Hipertensión arterial"
"hipertensión" in diagnostico.lower()  # verificar si contiene (insensible a mayúsculas)


In [ ]:
# Dividir un string en palabras
frase = "dolor de cabeza severo"
frase.split()  # divide por espacios, devuelve una lista


In [ ]:
# Contar caracteres en un string
len(medicamento)  # cuenta el número de caracteres o como de largo (length, len()) es un string


 ## Ejercicios: Strings (Cadenas de texto)



 ### Ejercicio 1



 Dado el medicamento: `farmaco = "Amoxicilina"`



 1. Muestra el medicamento en mayúsculas

 2. Muestra el medicamento en minúsculas

 3. Muestra la primera letra del medicamento

 4. Muestra la última letra del medicamento

In [ ]:
# Resultado ejercicio 1

# Dado el medicamento: farmaco = "Amoxicilina"
farmaco = "Amoxicilina"

# 1.-Muestra el medicamento en mayúsculas
farmaco_mayusc = farmaco.upper()
print(f"El nombre del medicamento en mayúsculas es: {farmaco_mayusc}")

# 2.-Muestra el medicamento en minúsculas
farmaco_minusc = farmaco.lower()
print(f"El nombre del medicamento en minúsculas es: {farmaco_minusc}")

# 3.-Muestra la primera letra del medicamento
primera_letra = farmaco[0]
print(f"La primera letra del medicamento es {primera_letra}")

# 4.-Muestra la última letra del medicamento
ultima_letra = farmaco[-1]
print(f"La última letra del medicamento es {ultima_letra}")

El nombre del medicamento en mayúsculas es: AMOXICILINA
El nombre del medicamento en minúsculas es: amoxicilina
La primera letra del medicamento es A
La última letra del medicamento es a


 ### Ejercicio 2



 Trabajando con nombres de pacientes:

 - `paciente = "María García López"`



 Realiza las siguientes operaciones:

 1. Reemplaza "María" por "Ana"

 2. Obtén solo los primeros 5 caracteres

 3. Obtén los caracteres desde la posición 6 hasta el final

 4. Obtén solo el apellido "García" usando índices (posiciones 6 a 11)

In [ ]:
# Resultado ejercicio 2

# Trabajando con nombres de pacientes:
paciente = "María García López"

# Realiza las siguientes operaciones:

# 1.- Reemplaza "María" por "Ana"
nuevo_nombre = paciente.replace("María", "Ana")
print(f"Nombre cambiado: {nuevo_nombre}")

# 2.- Obtén solo los primeros 5 caracteres
cinco_primeros_caracteres = paciente[0:5]
print(f"Los cinco primeros caracteres del nombre del paciente son: {cinco_primeros_caracteres}")

# 3.- Obtén los caracteres desde la posición 6 hasta el final
caracteres_del_sexto_al_final = paciente[6:]
print(f"Los caracteres desde la posición 6 hasta el final del nombre del paciente son: {caracteres_del_sexto_al_final}")

# 4.- Obtén solo el apellido "García" usando índices (posiciones 6 a 11)
apellido_garcia = paciente[6:12]
print(f"El primer apellido del paciente es: {apellido_garcia}")

Nombre cambiado: Ana García López
Los cinco primeros caracteres del nombre del paciente son: María
Los caracteres desde la posición 6 hasta el final del nombre del paciente son: García López
El primer apellido del paciente es: García


 ### Ejercicio 3



 Procesamiento de texto médico:

 1. Crea una variable `diagnostico = "  Hipertensión Arterial  "` (con espacios)

 2. Elimina los espacios del principio y final usando `.strip()`

 3. Convierte todo a minúsculas

 4. Reemplaza "arterial" por "sistémica"

 5. Verifica si la palabra "hipertensión" está en el diagnóstico usando `in`

 6. Cuenta cuántos caracteres tiene el diagnóstico final usando `len()`

 7. Divide el diagnóstico en palabras usando `.split()`

In [ ]:
# Resultado ejercicio 3

# Procesamiento de texto médico:

# 1.- Crea una variable diagnostico = " Hipertensión Arterial " (con espacios)
diagnostico = " Hipertensión Arterial "

# 2.- Elimina los espacios del principio y final usando .strip()
diagnostico_sin_espacios = diagnostico.strip()
print(f"El diagnóstico sin espacios es {diagnostico_sin_espacios}")

# 3.- Convierte todo a minúsculas
diagnostico_en_minusc = diagnostico_sin_espacios.lower()
print(f"El diagnóstico en minúsculas es {diagnostico_en_minusc}")

# 4.- Reemplaza "arterial" por "sistémica"
nuevo_diagnostico = diagnostico_en_minusc.replace("arterial","sistémica")
print(f"El nuevo diagnóstico es {nuevo_diagnostico}")

# 5.- Verifica si la palabra "hipertensión" está en el diagnóstico usando in
verificar_hipertensión = "hipertensión" in nuevo_diagnostico
print(f"¿Está hipertensión en el nuevo diagnóstico?: {verificar_hipertensión}")

# 6.- Cuenta cuántos caracteres tiene el diagnóstico final usando len()
numero_de_caracteres = len(nuevo_diagnostico)
print(f"El número de caracteres del diagnóstico final es {numero_de_caracteres}")

# 7.- Divide el diagnóstico en palabras usando split()
palabras_del_diagnostico = nuevo_diagnostico.split()
print(f"Las palabras del diagnóstico final son: {palabras_del_diagnostico}")


El diagnóstico sin espacios es Hipertensión Arterial
El diagnóstico en minúsculas es hipertensión arterial
El nuevo diagnóstico es hipertensión sistémica
¿Está hipertensión en el nuevo diagnóstico?: True
El número de caracteres del diagnóstico final es 22
Las palabras del diagnóstico final son: ['hipertensión', 'sistémica']


 ## Capitulo 5. Listas



 Una lista es una colección ordenada de elementos que pueden ser de diferentes tipos. Pueden contener integers, strings, Bools, None, otras listas y varias cosas más dentro.



 Las listas son mutables (se pueden modificar después de crearlas).



 Las listas son definidas por corchetes []


 Aviso: No confundir los corchetes que definen una lista con los corchetes de los indices. Aunque són el mismo simbolo, son cosas completamente distintas.

In [ ]:
# Crear listas
sintomas = ["fiebre", "tos", "dolor de garganta"]
temperaturas = [36.5, 37.2, 38.1, 37.8]
sintomas


In [ ]:
# Acceder a elementos por índice (empezando desde 0)
sintomas[0]  # primer elemento


In [ ]:
sintomas[-1]  # último elemento


In [ ]:
sintomas[1:3]  # elementos del índice 1 al 2


In [ ]:
# Métodos importantes de las listas
sintomas.append("fatiga")  # añadir al final
sintomas.append('tos')
sintomas


In [ ]:
sintomas.remove("tos")  # eliminar elemento específico que se llame "tos". Solo elimina el 1r elemento de la lista que se llame "tos", no todos ellos
sintomas


In [ ]:
len(sintomas)  # longitud de la lista (igual que posiamos mirar que longitud tiene el string dentro de una variable, lo podemos hacer con los elementos de una lista)
#Fijaros que la función len no nos esta dando la largada de los strings dentro de la lista, sino de los elementos de la lista en si


In [ ]:
# Operaciones útiles con listas numéricas
edades = [25, 34, 67, 45, 23, 56]
max(edades)  # valor máximo


In [ ]:
min(edades)  # valor mínimo


In [ ]:
sum(edades)  # suma de todos los elementos


las funciones max/min/sum en listas solo funcionan si TODOS los elementos de la lista son numeros (integers o floats), si alguno no lo es devolverá un error

In [ ]:
edades.append("cuarenta")
edades

In [ ]:
sum(edades)

In [ ]:
# Lista de listas
list = [["fiebre", 38.5], ["tos", True], ["dolor de garganta", False]]
list


In [ ]:
# Como accedemos con indices a los elementos de una lista de listas?
# si queremos acceder al valor 38.5
primer_elemento = list[0]
primer_elemento[1]
# esto nos dará el 2o elemento del 1r elemento de la lista

In [ ]:
# o analogamente lo podemos hacer de una sola vez en vez de guardar el primer elemento en una variable
list[0][1]


In [ ]:
# Evidentemente podemos guardar el valor al que hemos accedido mediante indices en una variable
valor_fiebre = list[0][1]
valor_fiebre


In [ ]:
# Operaciones adicionales con listas
numeros_ejemplo = [1, 2, 3, 2, 4, 2]

# Combinar listas con el operador +
lista1 = ["a", "b"]
lista2 = ["c", "d"]
lista_combinada = lista1 + lista2
lista_combinada


El metodo "in" que usabamos para saber si un string definido por nosotros estaba dentro de una variable de string, tambien funciona para las listas!!

Pero no de la misma manera, aquí lo que estamos preguntando a python és: hay algún elemento de la lista que sea igual a "a"? Nos responderá si es verdadero o falso.

In [ ]:
# Verificar si un elemento está en la lista
"a" in lista_combinada


In [ ]:
# Contar cuántas veces aparece un elemento (la función count() cuenta frecuencia de aparición del elemento en una lista)
numeros_ejemplo.count(2)


La función lista.index() nos devuelve el INDICE donde se ubica el elemento por el que hemos preguntado


In [ ]:
# Encontrar la posición de un elemento
numeros_ejemplo.index(3)  # encuentra la primera aparición



La función .pop() elimina y devuelve el último elemento.

In [ ]:
# Eliminar elementos de diferentes formas
lista_prueba = [10, 20, 30, 40]
lista_prueba.pop()


In [ ]:
lista_prueba  # ver la lista después de pop()


 ## Ejercicios: Listas



 ### Ejercicio 1



 Operaciones básicas con listas:



 1. Crea una lista llamada `medicamentos` que contenga: "Paracetamol", "Ibuprofeno", "Aspirina"

 2. Muestra el primer medicamento de la lista

 3. Muestra el último medicamento usando índice negativo

 4. Muestra cuántos medicamentos hay en la lista usando `len()`

In [ ]:
# Respuesta ejercicio 1

# Operaciones básicas con listas:

# 1.- Crea una lista llamada medicamentos que contenga: "Paracetamol", "Ibuprofeno", "Aspirina"
medicamentos = ["Paracetamol", "Ibuprofeno", "Aspirina"]

# 2.- Muestra el primer medicamento de la lista
primer_elemento = medicamentos[0]
print(f"El primer elemento de la lista es: {primer_elemento}")

# 3.- Muestra el último medicamento usando índice negativo
ultimo_elemento = medicamentos[-1]
print(f"El último medicamento de la lista es {ultimo_elemento}")

# 4.- Muestra cuántos medicamentos hay en la lista usando len()
numero_elementos = len(medicamentos)
print(f"El número de medicamentos en la lista es de {numero_elementos}")

El primer elemento de la lista es: Paracetamol
El último medicamento de la lista es Aspirina
El número de medicamentos en la lista es de 3


 ### Ejercicio 2



 Modificación de listas:



 1. Crea una lista `pacientes` con los nombres: "Ana", "Luis", "Carmen"

 2. Añade "Pedro" al final de la lista usando `append()`

 3. Elimina "Luis" de la lista usando `remove()`

 4. Muestra la lista final

 5. Muestra cuántos pacientes quedan en la lista

In [ ]:
# Respuesta ejercicio 2

# Modificación de listas:

# 1.- Crea una lista pacientes con los nombres: "Ana", "Luis", "Carmen"
pacientes = ["Ana", "Luis", "Carmen"]
print(f"La lista de pacientes es: {pacientes}")

# 2.- Añade "Pedro" al final de la lista usando append()
pacientes.append("Pedro")

# 3.- Elimina "Luis" de la lista usando remove()
pacientes.remove("Luis")

# 4.- Muestra la lista final
print(f"La lista final es: {pacientes}")

# 5.- Muestra cuántos pacientes quedan en la lista
numero_pacientes = len(pacientes)
print(f"El número de pacientes de la lista final es de {numero_pacientes}")

La lista de pacientes es: ['Ana', 'Luis', 'Carmen']
La lista final es: ['Ana', 'Carmen', 'Pedro']
El número de pacientes de la lista final es de 3


 ### Ejercicio de transición 2.5



 Práctica con acceso a elementos:



 1. Crea una lista `signos_vitales = [120, 80, 37.2, 75]`

 2. Accede y muestra cada elemento por separado

 3. Cambia la temperatura (tercer elemento) a 38.1

 4. Muestra la lista modificada

In [ ]:
# Respuesta ejercicio de transición 2.5

# Práctica con acceso a elementos:

# 1.- Crea una lista signos_vitales = [120, 80, 37.2, 75]
signos_vitales = [120, 80, 37.2, 75]

# 2.- Accede y muestra cada elemento por separado
primer_elemento = signos_vitales[0]
segundo_elemento = signos_vitales[1]
tercer_elemento = signos_vitales[2]
cuarto_elemento = signos_vitales[3]
print(f"El primer signo vital de la lista (tensión sistólica) es {primer_elemento}")
print(f"El segundo signo vital de la lista (tensión distólica) es {segundo_elemento}")
print(f"El tercer signo vital de la lista (temperatura) es {tercer_elemento}")
print(f"El cuarto signo vital de la lista (pulso) es {cuarto_elemento}")

# 3.- Cambia la temperatura (tercer elemento) a 38.1
signos_vitales[2] = 38.1

# 4.- Muestra la lista modificada
print(f"Los nuevos signos vitales son {signos_vitales}")

El primer signo vital de la lista (tensión sistólica) es 120
El segundo signo vital de la lista (tensión distólica) es 80
El tercer signo vital de la lista (temperatura) es 37.2
El cuarto signo vital de la lista (pulso) es 75
Los nuevos signos vitales son [120, 80, 38.1, 75]


 ### Ejercicio 3



 Acceso con índices:



 1. Crea una lista `datos_vitales` con estos valores: 36.8, 120, 80, 72

    (representan: temperatura, presión sistólica, presión diastólica, pulso)

 2. Accede y muestra la temperatura (primer elemento)

 3. Accede y muestra el pulso (último elemento)

 4. Obtén los valores de presión (elementos en posiciones 1 y 2) usando el indice [1:3]

 5. Cambia la temperatura a 37.2 asignando un nuevo valor a la primera posición

In [ ]:
# Respuesta ejercicio 3

# Acceso con índices:

# 1.- Crea una lista datos_vitales con estos valores: 36.8, 120, 80, 72
datos_vitales = [36.8, 120, 80, 72]
# (representan: temperatura, presión sistólica, presión diastólica, pulso)

# 2.- Accede y muestra la temperatura (primer elemento)
temperatura = datos_vitales[0]
print(f"La temperatura es de {temperatura}")

# 3.- Accede y muestra el pulso (último elemento)
pulso = datos_vitales[-1]
print(f"El pulso es de {pulso}")

# 4.- Obtén los valores de presión (elementos en posiciones 1 y 2) usando el indice [1:3]
presion = datos_vitales[1:3]
print(f"La presión es de {presion}")

# 5.- Cambia la temperatura a 37.2 asignando un nuevo valor a la primera posición
datos_vitales[0] = 37.2
print(f"Los nuevos datos son {datos_vitales}")


La temperatura es de 36.8
El pulso es de 72
La presión es de [120, 80]
Los nuevos datos son [37.2, 120, 80, 72]


 ### Ejercicio de transición 3.5



 Operaciones básicas con números:



 1. Crea una lista `pesos_basicos = [65.5, 70.2, 68.0]`

 2. Calcula y muestra la suma usando `sum()`

 3. Encuentra el mayor peso usando `max()`

 4. Cuenta cuántos elementos hay usando `len()`

In [ ]:
# Respuesta ejercicio de transición 3.5

# Operaciones básicas con números:

# 1.- Crea una lista pesos_basicos = [65.5, 70.2, 68.0]
pesos_basicos = [65.5, 70.2, 68.0]

# 2.- Calcula y muestra la suma usando sum()
suma = sum(pesos_basicos)
print(f"La suma de los pesos básicos es de {suma} kg")

# 3.- Encuentra el mayor peso usando max()
peso_maximo = max(pesos_basicos)
print(f"El peso máximo es de {peso_maximo} kg")

# 4.- Cuenta cuántos elementos hay usando len()
numero_pesos = len(pesos_basicos)
print(f"El número de pesos en la lista es de {numero_pesos}")

La suma de los pesos básicos es de 203.7 kg
El peso máximo es de 70.2 kg
El número de pesos en la lista es de 3


 ### Ejercicio 4



 Operaciones numéricas con listas:



 1. Crea una lista `pesos` con los valores: 65.5, 78.2, 90.1, 45.8, 72.0

 2. Calcula y muestra el peso máximo usando `max()`

 3. Calcula y muestra el peso mínimo usando `min()`

 4. Calcula y muestra el peso promedio dividiendo `sum(pesos)` entre `len(pesos)`

 5. Añade un nuevo peso de 68.5 a la lista

 6. Recalcula el promedio con la lista actualizada

In [ ]:
# Respuesta ejercicio 4

# Operaciones numéricas con listas:

# 1.- Crea una lista pesos con los valores: 65.5, 78.2, 90.1, 45.8, 72.0
pesos= [65.5, 78.2, 90.1, 45.8, 72.0]

# 2.- Calcula y muestra el peso máximo usando max()
peso_maximo = max(pesos)
print(f"El peso máximo es {peso_maximo} kg")

# 3.- Calcula y muestra el peso mínimo usando min()
peso_minimo = min(pesos)
print(f"El peso mínimo es {peso_minimo} kg")

# 4.- Calcula y muestra el peso promedio dividiendo sum(pesos) entre len(pesos)
peso_promedio = sum(pesos) / len(pesos)
print(f"El promedio de pesos es de {peso_promedio}")

# 5.- Añade un nuevo peso de 68.5 a la lista
pesos.append(68.5)
print(f"La nueva lista de pesos es {pesos}")

# 5.- Recalcula el promedio con la lista actualizada
peso_promedio_actualizado = sum(pesos) / len(pesos)
print(f"El nuevo promedio de pesos es de {peso_promedio_actualizado}")

El peso máximo es 90.1 kg
El peso mínimo es 45.8 kg
El promedio de pesos es de 70.32000000000001
La nueva lista de pesos es [65.5, 78.2, 90.1, 45.8, 72.0, 68.5]
El nuevo promedio de pesos es de 70.01666666666667


 ### Ejercicio 5



 Listas mixtas:



 1. Crea una lista llamada `historial` que contenga:

    - Un string: "Juan Pérez"

    - Un entero: 45

    - Un float: 75.5

    - Un boolean: True

 2. Accede y muestra cada elemento por separado usando índices

 3. Verifica el tipo de cada elemento usando `type()`

In [ ]:
# Respuesta ejercicio 5

# Listas mixtas:

# 1.- Crea una lista llamada historial que contenga:
# Un string: "Juan Pérez"
# Un entero: 45
# Un float: 75.5
# Un boolean: True

historial = ["Juan Pérez", 45, 75.5, True]

# 2.- Accede y muestra cada elemento por separado usando índices
primer_elemento = historial[0]
segundo_elemento = historial[1]
tercer_elemento = historial[2]
cuarto_elemento = historial[3]
print(f"El primer elemento de la lista (nombre) es {primer_elemento}")
print(f"El segundo elemento de la lista (edad) es {segundo_elemento}")
print(f"El tercer elemento de la lista (peso) es {tercer_elemento}")
print(f"El cuarto elemento de la lista es {cuarto_elemento}")

# 3.- Verifica el tipo de cada elemento usando type()
print(f"El tipo del primer elemento de la lista es {type(primer_elemento)}")
print(f"El tipo del segundo elemento de la lista es {type(segundo_elemento)}")
print(f"El tipo del tercer elemento de la lista es {type(tercer_elemento)}")
print(f"El tipo del cuarto elemento de la lista es {type(cuarto_elemento)}")

El primer elemento de la lista (nombre) es Juan Pérez
El segundo elemento de la lista (edad) es 45
El tercer elemento de la lista (peso) es 75.5
El cuarto elemento de la lista es True
El tipo del primer elemento de la lista es <class 'str'>
El tipo del segundo elemento de la lista es <class 'int'>
El tipo del tercer elemento de la lista es <class 'float'>
El tipo del cuarto elemento de la lista es <class 'bool'>


 ### Ejercicio de transición 5.5



 Trabajando con listas simples anidadas:



 1. Crea una lista `paciente_simple = ["María", 28]`

 2. Accede y muestra el nombre

 3. Accede y muestra la edad

 4. Cambia la edad a 29

 5. Borra la edad y guardala en la variable edad usando la función .pop()

In [ ]:
# Respuesta ejercicio de transición 5.5

# Trabajando con listas simples anidadas:

# 1.- Crea una lista paciente_simple = ["María", 28]
paciente_simple = ["María", 28]

# 2.- Accede y muestra el nombre
nombre = paciente_simple[0]
print(f"El nombre de la paciente es {nombre}")

# 3.- Accede y muestra la edad
edad = paciente_simple[-1]
print(f"La edad de la paciente es de {edad} años")

# 4.- Cambia la edad a 29
paciente_simple[1] = 29

# 5.- Borra la edad y guardala en la variable edad usando la función .pop()
edad = paciente_simple.pop()
print(f"La edad correcta de la paciente es de {edad} años")
print(f"El contenido final de la lista es {paciente_simple}")

El nombre de la paciente es María
La edad de la paciente es de 28 años
La edad correcta de la paciente es de 29 años
El contenido final de la lista es ['María']


 ### Ejercicio 6



 Listas anidadas (listas dentro de listas):



 1. Crea una lista `pacientes_datos` que contenga:

    - ["María", 28, 60.5]

    - ["Carlos", 35, 78.2]

    - ["Ana", 42, 65.0]

 2. Accede y muestra el nombre del segundo paciente

 3. Accede y muestra la edad del primer paciente

 4. Accede y muestra el peso del tercer paciente

 5. Cambia el peso de María (primer paciente) a 61.0

In [ ]:
# Respuesta ejercicio 6

# Listas anidadas (listas dentro de listas):

# Crea una lista pacientes_datos que contenga:
#["María", 28, 60.5]
#["Carlos", 35, 78.2]
#["Ana", 42, 65.0]
pacientes_datos = [["María", 28, 60.5],["Carlos", 35, 78.2],["Ana", 42, 65.0]]

# 1.- Accede y muestra el nombre del segundo paciente
segundo_paciente = pacientes_datos[1]
nombre_segundo_paciente = segundo_paciente[0]
print(f"El nombre del segundo paciente es {nombre_segundo_paciente}")

# 2.- Accede y muestra la edad del primer paciente
primer_paciente = pacientes_datos[0]
edad_primer_paciente = primer_paciente[1]
print(f"La edad del primer paciente es de {edad_primer_paciente} años")

# 3.- Accede y muestra el peso del tercer paciente
tercer_paciente = pacientes_datos[2]
peso_tercer_paciente = tercer_paciente[2]
print(f"El peso del tercer paciente es de {peso_tercer_paciente} kg")

# 4.- Cambia el peso de María (primer paciente) a 61.0
pacientes_datos[0][2] = 61.0
print(f"La lista corregida es {pacientes_datos}")

El nombre del segundo paciente es Carlos
La edad del primer paciente es de 28 años
El peso del tercer paciente es de 65.0 kg
La lista corregida es [['María', 28, 61.0], ['Carlos', 35, 78.2], ['Ana', 42, 65.0]]


 ### Ejercicio 7



 Manipulación avanzada:



 1. Crea dos listas:

    - `sintomas_mañana = ["fiebre", "tos"]`

    - `sintomas_tarde = ["dolor cabeza", "fatiga"]`

 2. Combina ambas listas en una nueva lista llamada `todos_sintomas` usando el operador `+`

 3. Añade "náuseas" al final de `todos_sintomas`

 4. Elimina "tos" de la lista

 5. Verifica si "fiebre" está en la lista usando `in`

 6. Cuenta cuántas veces aparece "fiebre" en la lista usando `.count()`

 7. Encuentra en qué posición está "fatiga" usando `.index()`

In [ ]:
# Respuesta ejercicio 7

# Manipulación avanzada:

# 1.- Crea dos listas:
# sintomas_mañana = ["fiebre", "tos"]
# sintomas_tarde = ["dolor cabeza", "fatiga"]
sintomas_mañana = ["fiebre", "tos"]
sintomas_tarde = ["dolor cabeza", "fatiga"]

# 2.- Combina ambas listas en una nueva lista llamada todos_sintomas usando el operador +
todos_sintomas = sintomas_mañana + sintomas_tarde

# 3.- Añade "náuseas" al final de todos_sintomas
todos_sintomas.append("náuseas")

# 4.- Elimina "tos" de la lista
todos_sintomas.remove("tos")
print(f"la lista final de sintomas es {todos_sintomas}")

# 5.- Verifica si "fiebre" está en la lista usando in
fiebre_esta = "fiebre" in todos_sintomas
print(f"¿Está fiebre entre los síntomas del paciente? {fiebre_esta}")

# 6.- Cuenta cuántas veces aparece "fiebre" en la lista usando .count()
fiebre_cuantas = todos_sintomas.count("fiebre")
print(f"El sintoma fiebre aparece {fiebre_cuantas} veces en la lista")

# 7.- Encuentra en qué posición está "fatiga" usando .index()
fatiga_posicion = todos_sintomas.index("fatiga")
print(f"La fatiga ocupa la posición {fatiga_posicion} en la lista")

la lista final de sintomas es ['fiebre', 'dolor cabeza', 'fatiga', 'náuseas']
¿Está fiebre entre los síntomas del paciente? True
El sintoma fiebre aparece 1 veces en la lista
La fatiga ocupa la posición 2 en la lista


 ### Ejercicio 8





 1. Crea una lista `consultas` que contenga:

    - ["09:00", "Juan", "Control rutinario"]

    - ["10:30", "María", "Dolor abdominal"]

    - ["12:00", "Pedro", "Revisión"]

 2. Muestra la hora de la primera consulta

 3. Muestra el motivo de la segunda consulta

 4. Cambia el nombre del tercer paciente de "Pedro" a "Antonio"

 5. Añade una nueva consulta: ["14:00", "Carmen", "Fiebre"]

 6. Muestra cuántas consultas hay programadas en total

In [ ]:
# Respuesta ejercicio 8

# 1.- Crea una lista consultas que contenga:
# ["09:00", "Juan", "Control rutinario"]
# ["10:30", "María", "Dolor abdominal"]
# ["12:00", "Pedro", "Revisión"]

consultas = [["09:00", "Juan", "Control rutinario"], ["10:30", "María", "Dolor abdominal"], ["12:00", "Pedro", "Revisión"]]

# 2.- Muestra la hora de la primera consulta
hora_primera_consulta = consultas[0][0]
print(f"La primera consulta es a las {hora_primera_consulta} horas")

# 3.- Muestra el motivo de la segunda consulta
motivo_segunda_consulta = consultas[1][2]
print(f"El motivo de la segunda consulta es {motivo_segunda_consulta}")

# 4.- Cambia el nombre del tercer paciente de "Pedro" a "Antonio"
consultas[2][1] = "Antonio"

# 5.- Añade una nueva consulta: ["14:00", "Carmen", "Fiebre"]
consultas.append(["14:00", "Carmen", "Fiebre"])

# 6.- Muestra cuántas consultas hay programadas en total
numero_consultas = len(consultas)
print(f"Hay {numero_consultas} consultas programadas")

La primera consulta es a las 09:00 horas
El motivo de la segunda consulta es Dolor abdominal
Hay 4 consultas programadas


 ### Ejercicio 9



 Creación y manipulación completa:



 1. Crea una lista vacía llamada `temperaturas`

 2. Añade estas temperaturas una por una: 36.5, 37.8, 36.9, 38.2, 37.1

 3. Calcula y muestra la temperatura promedio

 4. Encuentra la temperatura más alta y más baja

 6. Elimina la temperatura más alta de la lista

 7. Muestra la lista final y su nueva longitud

In [ ]:
# Respuesta ejercicio 9

# Creación y manipulación completa:

# 1.- Crea una lista vacía llamada temperaturas
temperaturas = []

# 2.- Añade estas temperaturas una por una: 36.5, 37.8, 36.9, 38.2, 37.1
temperaturas.append(36.5)
temperaturas.append(37.8)
temperaturas.append(36.9)
temperaturas.append(38.2)
temperaturas.append(37.1)

# 3.- Calcula y muestra la temperatura promedio
temperatura_promedio = sum(temperaturas) / len(temperaturas)
print(f"La temperatura promedio es de {temperatura_promedio} grados")

# 4.- Encuentra la temperatura más alta y más baja
temperatura_maxima = max(temperaturas)
temperatura_minima = min(temperaturas)
print(f"La temperatura más alta es de {temperatura_maxima} grados y la más baja de {temperatura_minima} grados")

# 5.- Elimina la temperatura más alta de la lista
temperaturas.remove(max(temperaturas))

# 6.- Muestra la lista final y su nueva longitud
longitud_lista_final = len(temperaturas)
print(f"La lista final de temperaturas es: {temperaturas} y su longitud es de {longitud_lista_final} elementos")

La temperatura promedio es de 37.3 grados
La temperatura más alta es de 38.2 grados y la más baja de 36.5 grados
La lista final de temperaturas es: [36.5, 37.8, 36.9, 37.1] y su longitud es de 4 elementos


 ### Ejercicio 10



 Desafío - Gestión de inventario médico:



 1. Crea una lista `inventario` con sublistas de medicamentos:

    - ["Paracetamol", 1000, "analgésico"]

    - ["Amoxicilina", 30, "antibiótico"]

    - ["Omeprazol", 25, "protector gástrico"]

 2. Cada sublista contiene: [nombre, cantidad, tipo]

 3. Muestra el nombre del segundo medicamento

 4. Actualiza la cantidad de Paracetamol a 45

 5. Añade un nuevo medicamento: ["Ibuprofeno", 600, "antiinflamatorio"]

 6. Calcula la cantidad total de mg de medicamentos sumando todas las cantidades

 7. Crea una nueva lista solo con los nombres de los medicamentos

 8. Verifica si hay algún medicamento con cantidad menor a 30

In [ ]:
# Respuesta ejercicio 10

# Desafío - Gestión de inventario médico:

# 1.- Crea una lista inventario con sublistas de medicamentos:
# ["Paracetamol", 1000, "analgésico"]
# ["Amoxicilina", 30, "antibiótico"]
# ["Omeprazol", 25, "protector gástrico"]
inventario = [["Paracetamol", 1000, "analgésico"], ["Amoxicilina", 30, "antibiótico"],["Omeprazol", 25, "protector gástrico"]]

# 2.- Cada sublista contiene: [nombre, cantidad, tipo]

# 3.- Muestra el nombre del segundo medicamento
nombre_segundo_medicamento = inventario[1][0]
print(f"El nombre del segundo medicamento es {nombre_segundo_medicamento}")

# 4.- Actualiza la cantidad de Paracetamol a 45
inventario[0][1] = 45

# 5.- Añade un nuevo medicamento: ["Ibuprofeno", 600, "antiinflamatorio"]
inventario.append(["Ibuprofeno", 600, "antiinflamatorio"])

# 6.- Calcula la cantidad total de mg de medicamentos sumando todas las cantidades
cantidad_total = (inventario[0][1] + inventario[1][1] + inventario[2][1] + inventario[3][1])
print(f"La cantidad total de medicamento es de {cantidad_total}")

# 7.- Crea una nueva lista solo con los nombres de los medicamentos
lista_de_nombres = [inventario[0][0], inventario[1][0], inventario[2][0], inventario[3][0]]
print(f"La lista de nombre es: {lista_de_nombres}")

# 8.- Verifica si hay algún medicamento con cantidad menor a 30

menor_30_p1 = inventario[0][1] < 30
menor_30_p2 = inventario[1][1] < 30
menor_30_p3 = inventario[2][1] < 30
menor_30_p4 = inventario[3][1] < 30

print(f"¿Paracetamol tiene menos de 30 mg?: {menor_30_p1}")
print(f"¿Amoxicilina tiene menos de 30 mg?: {menor_30_p2}")
print(f"¿Omeprazol tiene menos de 30 mg?: {menor_30_p3}")
print(f"¿Ibuprofeno tiene menos de 30 mg?: {menor_30_p4}")


El nombre del segundo medicamento es Amoxicilina
La cantidad total de medicamento es de 700
La lista de nombre es: ['Paracetamol', 'Amoxicilina', 'Omeprazol', 'Ibuprofeno']
¿Paracetamol tiene menos de 30 mg?: False
¿Amoxicilina tiene menos de 30 mg?: False
¿Omeprazol tiene menos de 30 mg?: True
¿Ibuprofeno tiene menos de 30 mg?: False


 ## Capitulo 6. Condicionales (if/elif/else) y Operadores Lógicos



 Las estructuras condicionales permiten que el programa tome decisiones basadas en condiciones.

 Python evalúa expresiones que pueden ser True (verdadero) o False (falso).



 ### Cómo funciona if/else:



 1. Python evalúa la condición después del `if`

 2. Si la condición es `True`, ejecuta el bloque de código indentado bajo el `if`

 3. Si la condición es `False`, se ejecutará el bloque de debajo (else) (si existe)

 4. El bloque "else" se ejecuta siempre si se llega allí. Es siempre el ultimo del condicional.

 4. Solo se ejecuta UNO DE LOS BLOQUES, NUNCA MÁS DE UNO.



 ### Sintaxis básica:

 ```python

 if condición:

     # código que se ejecuta si la condición es True

 else:

     # código que se ejecuta si la condición es False

 ```

In [ ]:
# Ejemplo básico: evaluar temperatura
temperatura = 37.8

if temperatura > 37.5:
    estado = "Fiebre detectada"
else:
    estado = "Temperatura normal"

estado


In [ ]:
# Ejemplo con temperatura normal
temperatura_normal = 36.8

if temperatura_normal > 37.5:
    estado = "Fiebre detectada"
else:
    estado = "Temperatura normal"

estado


 ### Condicionales múltiples con elif



 `elif` (else if) permite evaluar múltiples condiciones en secuencia.



 ### Cómo funciona if/elif/else:



 1. Python evalúa la primera condición (`if`)

 2. Si es `True`, ejecuta ese bloque y termina (no evalúa el resto)

 3. Si es `False`, pasa a la siguiente condición (`elif`)

 4. Repite el proceso para cada `elif` en orden

 5. Si ninguna condición es `True`, ejecuta el bloque `else` (si existe)

 6. **Solo se ejecuta un bloque**, el primero cuya condición sea verdadera



 ### Sintaxis:

 ```python

 if primera_condición:

     # código para primera_condición

 elif segunda_condición:

     # código para segunda_condición

 elif tercera_condición:

     # código para tercera_condición

 else:

     # código si ninguna condición es verdadera

 ```

In [ ]:
# Ejemplo: clasificar presión arterial
presion_sistolica = 140

if presion_sistolica >= 180:
    categoria = "Crisis hipertensiva"
elif presion_sistolica >= 140:
    categoria = "Hipertensión grado 1"
elif presion_sistolica >= 130:
    categoria = "Presión arterial elevada"
else:
    categoria = "Presión arterial normal"

f"Presión: {presion_sistolica} mmHg - {categoria}"


In [ ]:
# Otro ejemplo con diferentes valores
presion_normal = 115

if presion_normal >= 180:
    categoria = "Crisis hipertensiva"
elif presion_normal >= 140:
    categoria = "Hipertensión grado 1"
elif presion_normal >= 130:
    categoria = "Presión arterial elevada"
else:
    categoria = "Presión arterial normal"

f"Presión: {presion_normal} mmHg - {categoria}"


La condición que incluimos en un bloque if/elif/else puede ser simple (presion_normal >= 180) o  compuesta...

Aquí es donde entran la combinación de operadores lógicos, donde solo se cumplirá la condición si la combinación de sus condiciónes internas es True

 ### Operadores lógicos: and, or, not



 Los operadores lógicos permiten combinar múltiples condiciones:



 - **`and`**: Ambas condiciones deben ser `True` para que el resultado sea `True`

 - **`or`**: Al menos una condición debe ser `True` para que el resultado sea `True`

 - **`not`**: Invierte el valor booleano (`True` se convierte en `False` y viceversa)



 ### Tabla de verdad para `and`:

 - `True and True` = `True`

 - `True and False` = `False`

 - `False and True` = `False`

 - `False and False` = `False`

 Si os fijais, con 'and' las dos condiciónes booleanas tienen que ser true para que el resultado sea true

 ### Tabla de verdad para `or`:

 - `True or True` = `True`

 - `True or False` = `True`

 - `False or True` = `True`

 - `False or False` = `False`


 En cambio con el operador 'or', con que una de las dos sea True el resultado ya es True

In [ ]:
# Ejemplo con and: ambas condiciones deben cumplirse
temperatura = 38.2
tiene_tos = True

if temperatura > 37.5 and tiene_tos:
    diagnostico = "Posible infección respiratoria"
else:
    diagnostico = "Síntomas no concluyentes"

diagnostico


In [ ]:
# Ejemplo con or: al menos una condición debe cumplirse
temperatura_baja = 36.8
dolor_garganta = True

if temperatura_baja > 37.5 or dolor_garganta:
    diagnostico = "Requiere evaluación"
else:
    diagnostico = "Sin síntomas preocupantes"

diagnostico


In [ ]:
# Ejemplo con not: invertir condición
paciente_alergico = False

if not paciente_alergico:
    medicamento_permitido = "Puede recibir penicilina"
else:
    medicamento_permitido = "NO dar penicilina"

medicamento_permitido


 ## Ejercicios capitulo 6: Condicionales (if/elif/else) + Operadores logicos



 ### Ejercicio 1



 Evaluación básica de temperatura:



 1. Crea una variable `temperatura` con el valor 38.5

 2. Usa un condicional if/else para determinar si hay fiebre (temperatura > 37.5)

 3. Guarda el resultado en una variable `estado` y muéstrala

 4. Prueba el mismo código con `temperatura = 36.8`

In [ ]:
from ast import If
from types import EllipsisType
# Respuesta ejercicio 1

# Evaluación básica de temperatura:

# 1.- Crea una variable temperatura con el valor 38.5
temperatura = 38.5

# 2.- Usa un condicional if/else para determinar si hay fiebre (temperatura > 37.5)
# 3.- Guarda el resultado en una variable estado y muéstrala
if temperatura > 37.5:
  estado = "fiebre"

else:
  estado = "temperatura normal"

print(f"El paciente tiene {estado}")

# 4.- Prueba el mismo código con temperatura = 36.8
temperatura = 36.8

if temperatura > 37.5:
  estado = "fiebre"

else:
  estado = "temperatura normal"

print(f"El paciente tiene {estado}")


El paciente tiene fiebre
El paciente tiene temperatura normal


 ### Ejercicio de transición 1.5



 Práctica con condiciones simples:



 1. Crea una variable `edad = 20`

 2. Determina si es "Mayor de edad" o "Menor de edad" (límite en 18)

 3. Prueba con `edad = 16`

In [ ]:
# Respuesta ejercicio de transición 1.5
# Práctica con condiciones simples:
# 1.- Crea una variable edad = 20
# 2.- Determina si es "Mayor de edad" o "Menor de edad" (límite en 18)
edad = 20

if edad > 18:
  mayoria_de_edad = True
else:
  mayoria_de_edad = False

print(f"¿La persona es mayor de edad?: {mayoria_de_edad}")

# 3.- Prueba con edad = 16
edad = 16

if edad > 18:
  mayoria_de_edad = True
else:
  mayoria_de_edad = False

print(f"¿La persona es mayor de edad?: {mayoria_de_edad}")

¿La persona es mayor de edad?: True
¿La persona es mayor de edad?: False


 ### Ejercicio 2



 Clasificación de edad de pacientes:



 1. Crea una variable `edad` con el valor 25

 2. Usa if/elif/else para clasificar al paciente:

    - Si edad < 18: "Pediátrico"

    - Si edad >= 18 y edad < 65: "Adulto"

    - Si edad >= 65: "Adulto mayor"

 3. Guarda el resultado en `categoria` y muéstralo

 4. Prueba con edades: 15, 45, 70

In [ ]:
# Respuesta ejercicio 2

# Clasificación de edad de pacientes:

# 1.- Crea una variable edad con el valor 25
edad = 25

# 2.- Usa if/elif/else para clasificar al paciente:
# Si edad < 18: "Pediátrico"
# Si edad >= 18 y edad < 65: "Adulto"
# Si edad >= 65: "Adulto mayor"

# 3.- Guarda el resultado en categoria y muéstralo
if edad < 18:
  clase_paciente = "Pediátrico"
elif edad >= 18 and edad < 65:
  clase_paciente = "Adulto"
else:
  clase_paciente = "Adulto mayor"

print(f"La clase del paciente es {clase_paciente}")

# 4.- Prueba con edades: 15, 45, 70
edad = 15
if edad < 18:
  clase_paciente = "Pediátrico"
elif edad >= 18 and edad < 65:
  clase_paciente = "Adulto"
else:
  clase_paciente = "Adulto mayor"

print(f"La clase del paciente es {clase_paciente}")

edad = 45
if edad < 18:
  clase_paciente = "Pediátrico"
elif edad >= 18 and edad < 65:
  clase_paciente = "Adulto"
else:
  clase_paciente = "Adulto mayor"

print(f"La clase del paciente es {clase_paciente}")

edad = 70
if edad < 18:
  clase_paciente = "Pediátrico"
elif edad >= 18 and edad < 65:
  clase_paciente = "Adulto"
else:
  clase_paciente = "Adulto mayor"

print(f"La clase del paciente es {clase_paciente}")

La clase del paciente es Adulto
La clase del paciente es Pediátrico
La clase del paciente es Adulto
La clase del paciente es Adulto mayor


 ### Ejercicio de transición 2.5



 Clasificación simple de IMC:



 1. Crea una variable `imc = 22.5`

 2. Clasifica usando if/elif/else:

    - Si IMC < 18.5: "Bajo peso"

    - Si IMC < 25: "Normal"

    - Si IMC >= 25: "Sobrepeso"

 3. Prueba con valores: 17, 23, 27

In [ ]:
# Respuesta ejercicio de transición 2.5

# Clasificación simple de IMC:

# 1.- Crea una variable imc = 22.5
imc = 22.5

# 2.- Clasifica usando if/elif/else:
# Si IMC < 18.5: "Bajo peso"
# Si IMC < 25: "Normal"
# Si IMC >= 25: "Sobrepeso"

if imc < 18.5:
  clase_peso = "Bajo peso"
elif imc >= 18.5 and imc < 25:
  clase_peso = "Normal"
else:
  clase_peso = "Sobrepeso"

print(f"El IMC del paciente indica que el paciente tiene una clasificación de {clase_peso}")


# 3.- Prueba con valores: 17, 23, 27
imc = 17
if imc < 18.5:
  clase_peso = "Bajo peso"
elif imc >= 18.5 and imc < 25:
  clase_peso = "Normal"
else:
  clase_peso = "Sobrepeso"

print(f"El IMC del paciente indica que el paciente tiene una clasificación de {clase_peso}")

imc = 23
if imc < 18.5:
  clase_peso = "Bajo peso"
elif imc >= 18.5 and imc < 25:
  clase_peso = "Normal"
else:
  clase_peso = "Sobrepeso"

print(f"El IMC del paciente indica que el paciente tiene una clasificación de {clase_peso}")
imc = 27
if imc < 18.5:
  clase_peso = "Bajo peso"
elif imc >= 18.5 and imc < 25:
  clase_peso = "Normal"
else:
  clase_peso = "Sobrepeso"

print(f"El IMC del paciente indica que el paciente tiene una clasificación de {clase_peso}")

El IMC del paciente indica que el paciente tiene una clasificación de Normal
El IMC del paciente indica que el paciente tiene una clasificación de Bajo peso
El IMC del paciente indica que el paciente tiene una clasificación de Normal
El IMC del paciente indica que el paciente tiene una clasificación de Sobrepeso


 ### Ejercicio 3



 Evaluación de presión arterial:



 1. Crea una variable `presion_sistolica` con el valor 135

 2. Clasifica la presión usando if/elif/else:

    - Si >= 180: "Crisis hipertensiva"

    - Si >= 140: "Hipertensión grado 1"

    - Si >= 130: "Presión elevada"

    - Si < 130: "Normal"

 3. Muestra el resultado con un f-string: "Presión {valor} mmHg: {categoria}"

 4. Prueba con valores: 120, 145, 185

In [ ]:
# Respuesta ejercicio 3

# Evaluación de presión arterial:

# 1.- Crea una variable presion_sistolica con el valor 135
presion_sistolica = 135

# 2.- Clasifica la presión usando if/elif/else:
# Si >= 180: "Crisis hipertensiva"
# Si >= 140: "Hipertensión grado 1"
# Si >= 130: "Presión elevada"
# Si < 130: "Normal"

# 3.- Muestra el resultado con un f-string: "Presión {valor} mmHg: {categoria}"
if presion_sistolica >= 180:
  clase_presion = "Crisis hipertensiva"
elif presion_sistolica < 180 and presion_sistolica >= 140:
  clase_presion = "Hipertensión grado 1"
elif presion_sistolica < 140 and presion_sistolica >= 130:
  clase_presion = "Presión elevada"
else:
  clase_presion = "Normal"

print(f"Presión {presion_sistolica} mmHg: {clase_presion}")

# 4.-Prueba con valores: 120, 145, 185
presion_sistolica = 120
if presion_sistolica >= 180:
  clase_presion = "Crisis hipertensiva"
elif presion_sistolica < 180 and presion_sistolica >= 140:
  clase_presion = "Hipertensión grado 1"
elif presion_sistolica < 140 and presion_sistolica >= 130:
  clase_presion = "Presión elevada"
else:
  clase_presion = "Normal"

print(f"Presión {presion_sistolica} mmHg: {clase_presion}")

presion_sistolica = 145
if presion_sistolica >= 180:
  clase_presion = "Crisis hipertensiva"
elif presion_sistolica < 180 and presion_sistolica >= 140:
  clase_presion = "Hipertensión grado 1"
elif presion_sistolica < 140 and presion_sistolica >= 130:
  clase_presion = "Presión elevada"
else:
  clase_presion = "Normal"

print(f"Presión {presion_sistolica} mmHg: {clase_presion}")

presion_sistolica = 185
if presion_sistolica >= 180:
  clase_presion = "Crisis hipertensiva"
elif presion_sistolica < 180 and presion_sistolica >= 140:
  clase_presion = "Hipertensión grado 1"
elif presion_sistolica < 140 and presion_sistolica >= 130:
  clase_presion = "Presión elevada"
else:
  clase_presion = "Normal"

print(f"Presión {presion_sistolica} mmHg: {clase_presion}")

Presión 135 mmHg: Presión elevada
Presión 120 mmHg: Normal
Presión 145 mmHg: Hipertensión grado 1
Presión 185 mmHg: Crisis hipertensiva


 ### Ejercicio 4



 Operadores lógicos básicos:



 1. Define variables: `tiene_fiebre = True` y `tiene_tos = False`

 2. Crea condicionales para evaluar:

    - Si tiene fiebre AND tos: "Probable infección"

    - Si tiene fiebre OR tos: "Síntomas presentes"

    - Si NO tiene fiebre: "Sin fiebre"

 3. Prueba las tres condiciones por separado

In [ ]:
# Respuesta ejercicio 4

# Operadores lógicos básicos:

# 1.- Define variables: tiene_fiebre = True y tiene_tos = False
tiene_fiebre = True
tiene_tos = False

# 2.- Crea condicionales para evaluar:
# Si tiene fiebre AND tos: "Probable infección"
# Si tiene fiebre OR tos: "Síntomas presentes"
# Si NO tiene fiebre: "Sin fiebre"

if tiene_fiebre and tiene_tos:
  sospecha_clinica = "Probable infección"
elif not tiene_fiebre:
  sospecha_clinica = "Sin fiebre"
elif tiene_fiebre or tiene_tos:
  sospecha_clinica = "Sintomas presentes"

print(f"La situación clínica es {sospecha_clinica}")

# 4.- Prueba las tres condiciones por separado
tiene_fiebre = False
tiene_tos = False
if tiene_fiebre and tiene_tos:
  sospecha_clinica = "Probable infección"
elif not tiene_fiebre:
  sospecha_clinica = "Sin fiebre"
elif tiene_fiebre or tiene_tos:
  sospecha_clinica = "Sintomas presentes"

print(f"La situación clínica es {sospecha_clinica}")

tiene_fiebre = False
tiene_tos = True
if tiene_fiebre and tiene_tos:
  sospecha_clinica = "Probable infección"
elif not tiene_fiebre:
  sospecha_clinica = "Sin fiebre"
elif tiene_fiebre or tiene_tos:
  sospecha_clinica = "Sintomas presentes"

print(f"La situación clínica es {sospecha_clinica}")

tiene_fiebre = True
tiene_tos = True
if tiene_fiebre and tiene_tos:
  sospecha_clinica = "Probable infección"
elif not tiene_fiebre:
  sospecha_clinica = "Sin fiebre"
elif tiene_fiebre or tiene_tos:
  sospecha_clinica = "Sintomas presentes"

print(f"La situación clínica es {sospecha_clinica}")

La situación clínica es Sintomas presentes
La situación clínica es Sin fiebre
La situación clínica es Sin fiebre
La situación clínica es Probable infección


 ### Ejercicio de transición 4.5



 Práctica con operadores lógicos simples:



 1. Define: `es_adulto = True` y `tiene_seguro = False`

 2. Evalúa si puede recibir tratamiento gratuito:

    - Si es adulto AND tiene seguro: "Tratamiento con seguro"

    - Si es adulto AND NO tiene seguro: "Tratamiento particular"

    - Sino: "Consultar pediatría"

In [ ]:
# Respuesta ejercicio de transición 4.5
# Práctica con operadores lógicos simples:

# 1.- Define: es_adulto = True y tiene_seguro = False
es_adulto = True
tiene_seguro = False

# 2.- Evalúa si puede recibir tratamiento gratuito:
#Si es adulto AND tiene seguro: "Tratamiento con seguro"
#Si es adulto AND NO tiene seguro: "Tratamiento particular"
#Sino: "Consultar pediatría"
if not es_adulto:
  tratamiento_gratuito = "Consultar pediatria"
if es_adulto and tiene_seguro:
  tratamiento_gratuito = "Tratamiento con seguro"
if es_adulto and not tiene_seguro:
  tratamiento_gratuito = "Tratamiento particular"
print(f"¿Puede recibir tratamiento gratuito?: {tratamiento_gratuito}")


¿Puede recibir tratamiento gratuito?: Tratamiento particular


 ### Ejercicio 5



 Evaluación múltiple de signos vitales:



 1. Define: `temperatura = 38.1`, `pulso = 95`, `presion = 130`

 2. Usa operadores lógicos para determinar:

    - Si hay fiebre (temp > 37.5) AND taquicardia (pulso > 100): "Alerta alta"

    - Si hay fiebre OR hipertensión (presión >= 140): "Requiere monitoreo"

    - Si todo está normal: "Signos vitales normales"

 3. Usa una estructura if/elif/else para mostrar solo un resultado

In [ ]:
# Respuesta ejercicio 5
# Evaluación múltiple de signos vitales:
# 1.-Define: temperatura = 38.1, pulso = 95, presion = 130
temperatura = 38.1
pulso = 95
presion = 130

# 2.- Usa operadores lógicos para determinar:
# Si hay fiebre (temp > 37.5) AND taquicardia (pulso > 100): "Alerta alta"
# Si hay fiebre OR hipertensión (presión >= 140): "Requiere monitoreo"
# Si todo está normal: "Signos vitales normales"

# 3.- Usa una estructura if/elif/else para mostrar solo un resultado

fiebre = False
taquicardia = False
hipertension = False

if temperatura > 37.5:
  fiebre = True
if pulso > 100:
  taquicardia = True
if presion >= 140:
  hipertension = True

if not fiebre and not taquicardia and not hipertension:
  estado_paciente = "Signos vitales normales"
elif fiebre and taquicardia:
  estado_paciente = "Alerta alta"
elif fiebre or hipertension:
  estado_paciente = "Requiere monitoreo"
else:
  estado_paciente = "Taquicardia"

print (f"Estado del paciente: {estado_paciente}")





Estado del paciente: Signos vitales normales


 ### Ejercicio 6



 Calculadora de IMC con clasificación:



 1. Define `peso = 75` y `altura = 1.70`

 2. Calcula el IMC: `imc = peso / (altura ** 2)`

 3. Clasifica usando if/elif/else:

    - Si IMC < 18.5: "Bajo peso"

    - Si IMC < 25: "Normal"

    - Si IMC < 30: "Sobrepeso"

    - Si IMC >= 30: "Obesidad"

 4. Muestra: "IMC: {valor} - Clasificación: {categoria}"

In [ ]:
# Respuesta ejercicio 6

# Calculadora de IMC con clasificación:

# 1.- Define peso = 75 y altura = 1.70
peso = 75
altura = 1.70

# 2.- Calcula el IMC: imc = peso / (altura ** 2)
imc = peso / (altura ** 2)

# 3.- Clasifica usando if/elif/else:
# Si IMC < 18.5: "Bajo peso"
# Si IMC < 25: "Normal"
# Si IMC < 30: "Sobrepeso"
# Si IMC >= 30: "Obesidad"

if imc < 18.5:
  clase_peso = "Bajo peso"
elif imc >= 18.5 and imc < 25:
  clase_peso = "Normal"
elif imc >= 25 and imc < 30:
  clase_peso = "Sobrepeso"
else:
  clase_peso = "Obesidad"

# 4.- Muestra: "IMC: {valor} - Clasificación: {categoria}"
print(f"IMC: {imc} - Clasificación: {clase_peso}")

IMC: 25.95155709342561 - Clasificación: Sobrepeso


 ### Ejercicio 7



 Sistema de triaje hospitalario:



 1. Define variables: `edad = 75`, `temperatura = 39.2`, `dolor_pecho = True`

 2. Determina la prioridad usando if/elif/else:

    - Si edad > 70 AND temperatura > 38.5: "Prioridad 1 - Urgente"

    - Si dolor_pecho OR temperatura > 39: "Prioridad 2 - Alto"

    - Si temperatura > 37.5: "Prioridad 3 - Medio"

    - Sino: "Prioridad 4 - Bajo"

 3. Prueba con diferentes combinaciones de valores

In [ ]:
# Respuesta ejercicio 7


 ### Ejercicio 8



 Validación de medicamentos:



 1. Define: `alergico_penicilina = True`, `edad = 65`, `embarazada = False`

 2. Para el medicamento "Amoxicilina" (derivado de penicilina):

    - Si alérgico a penicilina: "CONTRAINDICADO - Alergia"

    - Si embarazada AND edad < 30: "Consultar con especialista"

    - Si edad > 70: "Reducir dosis"

    - Sino: "Medicamento aprobado"

 3. Cambia los valores y prueba diferentes escenarios

In [ ]:
# Respuesta ejercicio 8


 ### Ejercicio 9



 Evaluación de laboratorio:



 1. Define: `glucosa = 110`, `colesterol = 220`, `trigliceridos = 180`

 2. Evalúa cada parámetro por separado:

    - Glucosa: Normal (<100), Prediabetes (100-125), Diabetes (>125)

    - Colesterol: Deseable (<200), Límite (200-239), Alto (>=240)

    - Triglicéridos: Normal (<150), Límite (150-199), Alto (>=200)

 3. Crea un resumen que muestre los tres resultados

In [ ]:
# Respuesta ejercicio 9
# Evaluación de laboratorio:

# 1.- Define: glucosa = 110, colesterol = 220, trigliceridos = 180
glucosa = 110
colesterol = 220
trigliceridos = 180

# 2.- Evalúa cada parámetro por separado:
# Glucosa: Normal (<100), Prediabetes (100-125), Diabetes (>125)
# Colesterol: Deseable (<200), Límite (200-239), Alto (>=240)
# Triglicéridos: Normal (<150), Límite (150-199), Alto (>=200)

if glucosa < 100:
  glucemia = "Normal"
elif glucosa >= 100 and glucosa < 125:
  glucemia = "Prediabetes"
else:
  glucemia = "Diabetes"

if colesterol < 200:
  colesterolemia = "Deseable"
elif colesterol >= 200 and colesterol < 240:
  colesterolemia = "Límite"
else:
  colesterolemia = "Alto"

if trigliceridos < 150:
  trigliceridemia = "Normal"
elif trigliceridos >= 150 and trigliceridos < 200:
  trigliceridemia = "Límite"
else:
  trigliceridemia = "Alto"

# 3.- Crea un resumen que muestre los tres resultados
print(f"Resultados analíticos:")
print(f"Glucosa:   Valor: {glucosa} mg. (<  100) Valoración: {glucemia}")
print(f"Colesterol:   Valor: {colesterol} mg. ( 200 - 239) Valoración: {colesterolemia}")
print(f"Triglicéridos:   Valor: {trigliceridos} mg. ( 150-199) Valoración: {trigliceridemia}")

Resultados analíticos:
Glucosa:   Valor: 110 mg. (<  100) Valoración: Prediabetes
Colesterol:   Valor: 220 mg. ( 200 - 239) Valoración: Límite
Triglicéridos:   Valor: 180 mg. ( 150-199) Valoración: Límite


 ### Ejercicio 10



 Sistema complejo de diagnóstico:



 1. Define múltiples síntomas y signos:

    - `fiebre = True`, `tos = True`, `dolor_garganta = False`

    - `temperatura = 38.8`, `dias_sintomas = 3`

 2. Crea un sistema de diagnóstico:

    - Si fiebre AND tos AND temperatura > 38.5: "Probable gripe"

    - Si fiebre AND dolor_garganta: "Posible faringitis"

    - Si tos AND NOT fiebre: "Tos seca - revisar alergias"

    - Si días_síntomas > 7: "Síntomas prolongados - consulta médica"

    - Si solo fiebre: "Fiebre inespecífica"

    - Sino: "Síntomas menores"

 3. El sistema debe evaluar en orden de prioridad y mostrar solo un diagnóstico

In [ ]:
# Respuesta ejercicio 10
# Sistema complejo de diagnóstico:

# 1.- Define múltiples síntomas y signos:

fiebre = False
tos = False
dolor_garganta = False

fiebre = True
tos = True

temperatura = 38.8
dias_sintomas = 3

# 2.- Crea un sistema de diagnóstico:
# Si fiebre AND tos AND temperatura > 38.5: "Probable gripe"
# Si fiebre AND dolor_garganta: "Posible faringitis"
# Si tos AND NOT fiebre: "Tos seca - revisar alergias"
# Si dias_sintomas > 7: "Síntomas prolongados - consulta médica"
# Si solo fiebre: "Fiebre inespecífica"
# Sino: "Síntomas menores"


if dias_sintomas > 7:
    diagnostico = "Síntomas prolongados - consulta médica"
elif fiebre and tos and temperatura > 38.5:
    diagnostico = "Probable gripe"
elif fiebre and dolor_garganta:
    diagnostico = "Posible faringitis"
elif tos and not fiebre:
    diagnostico = "Tos seca - revisar alergias"
elif fiebre and not tos and not dolor_garganta:
    diagnostico = "Fiebre inespecífica"
else:
    diagnostico = "Síntomas menores"

# 3.- El sistema debe evaluar en orden de prioridad y mostrar solo un diagnóstico
print (f"Diagnóstico preliminar: {diagnostico}")

Diagnóstico preliminar: Probable gripe


 ## Capitulo 7. Bucles



 Los bucles permiten ejecutar un bloque de código repetidamente (de manera iterativa).



 ### Bucle for



 El bucle `for` se usa para iterar sobre una secuencia (lista, string, etc.).



 ### Cómo funciona el bucle for:



 1. Toma el primer elemento de la secuencia

 2. Asigna ese elemento a la variable del bucle

 3. Ejecuta el bloque de código indentado

 4. Toma el siguiente elemento y repite los pasos 2-3

 5. Continúa hasta que no hay más elementos

 6. Sale del bucle



 ### Sintaxis básica:

 ```python

 for variable in secuencia:

     # código que se ejecuta para cada elemento de la secuancia

 ```



 La variable del bucle toma el valor de cada elemento en cada iteración.

In [ ]:
nombre = 'Maria Antonieta'

for letra in nombre:
    print(letra)

M
a
r
i
a
 
A
n
t
o
n
i
e
t
a


In [ ]:
# Ejemplo básico: iterar sobre una lista
medicamentos = ["Ibuprofeno", "Paracetamol", "Amoxicilina"]

for medicamento in medicamentos:
    # En cada vuelta, 'medicamento' toma un valor diferente
    print(medicamento)


#Fijaros que imprime uno debajo del otro porque ha entrado tres veces al bucle, una para cada elemento de la lista

Ibuprofeno
Paracetamol
Amoxicilina


Combinando el valor de dentro de la variable con un string usando el metodo f-string (f"texto_que_quiera{variable}")

In [ ]:
# Ejemplo con temperaturas
temperaturas = [36.8, 37.2, 38.1, 37.5]

for temp in temperaturas:
    if temp > 37.5:
        estado = f"Temperatura {temp}°C - FIEBRE"
    else:
        estado = f"Temperatura {temp}°C - Normal"
    print(estado)


# Fijaros que con el metodo f-string, hemos cojido cada elemento de la lista temperaturas, que era un numero floar,
# y con el f-string lo hemos introducido dentro de un string, devolviendo al final un unico string



Temperatura 36.8°C - Normal
Temperatura 37.2°C - Normal
Temperatura 38.1°C - FIEBRE
Temperatura 37.5°C - Normal


 ### Función range()



 `range()` genera una secuencia de números. Es muy útil con bucles `for`.



 - `range(n)`: genera números del 0 al n-1

 - `range(inicio, fin)`: genera números desde inicio hasta fin-1

 - `range(inicio, fin, paso)`: genera números con un incremento específico



 **Importante**: el número final nunca se incluye.

In [ ]:
# Ejemplos de range()
for element in range(5):
    print(element)  # del 0 al 4


0
1
2
3
4


In [ ]:
for element in range(2, 8):
    print(element)  # del 2 al 7


2
3
4
5
6
7


In [ ]:
for element in range(0, 10, 2):
    print(element)    # del 0 al 8, de 2 en 2



0
2
4
6
8


In [ ]:
# Usar range() con for para crear horarios
for hora in range(9, 13):  # de 9 a 12
    print(f"Consulta a las {hora}:00")


Consulta a las 9:00
Consulta a las 10:00
Consulta a las 11:00
Consulta a las 12:00


### Combinación de bucle for con listas y el metodo .append()

In [ ]:
peso = [45, 50, 62, 48, 70]

peso_cuadrado = []

for element in peso:
    peso_cuadrado.append(element**2)


peso_cuadrado #Fijaros que hemos iterado sobre cada elemento de la lista peso, hemos hecho el cuadrado de cada elemento uno a uno, y lo hemos ido
#guardando en una lista vacia llamada 'peso_cuadrado'

[2025, 2500, 3844, 2304, 4900]

 ### Función enumerate()



 `enumerate()` devuelve tanto el índice como el valor de cada elemento en una secuencia.

 Es útil cuando necesitas saber la posición del elemento además de su valor.

In [ ]:
# Ejemplo con enumerate()
pacientes = ["Ana García", "Luis Pérez", "Carmen López"]

for indice, nombre in enumerate(pacientes):
    print(f"Posición {indice}: {nombre}")


Posición 0: Ana García
Posición 1: Luis Pérez
Posición 2: Carmen López


 ### Bucle while



 El bucle `while` repite un bloque de código mientras una condición sea verdadera. En contraposición al bucle for que repite el bloque de codigo una vez por cada elemento de nuestra secuencia.



 ### Cómo funciona while:



 1. Evalúa la condición

 2. Si es `True`, ejecuta el bloque de código

 3. Vuelve al paso 1 (reevalúa la condición)

 4. Si es `False`, sale del bucle



 ### Sintaxis:

 ```python

 while condición:

     # código que se repite

     # IMPORTANTE: algo debe cambiar la condición para evitar bucle infinito

 ```



 **¡Cuidado!**: Siempre debe haber algo dentro del bucle que eventualmente haga la condición `False`, sino el bucle será infinito.

In [ ]:
# Ejemplo básico de while
contador = 0

while contador < 3:
    f"Paciente {contador + 1} atendido"
    contador += 1  # CRUCIAL: cambiar la variable de control


In [ ]:
# El valor final del contador
contador


# Si os fijais, lo que hacemos es dentro del bucle while vamos modificando la variable de condición, para que al llegar a un determinado punto de
# interés el bucle acabe

 ### Control de flujo: break y continue



 - **`break`**: Sale inmediatamente del bucle, sin importar si la condición sigue siendo verdadera. No se ejecutará ninguna otra parte del bucle después del break.

 - **`continue`**: Salta el resto del código en la iteración actual y va a la siguiente iteración



 Estos comandos solo funcionan dentro de bucles.

In [ ]:
# Ejemplo de break: parar cuando se encuentra algo específico
temperaturas = [36.8, 37.2, 39.5, 37.1, 36.9]

for temp in temperaturas:
    if temp > 39.0:
        resultado = f"FIEBRE ALTA detectada: {temp}°C - Parar revisión"
        break
    resultado = f"Temperatura {temp}°C - Normal"

resultado

#En este codigo lo que estamos haciendo de facto es encontrar el primer elemento de la lista temperatura que sea mayor a 39. Una vez hemos encontrado
# el primero el bucle para, sin mirar si hay otras temperaturas que también cumplan la condición

In [ ]:
# Ejemplo de continue: saltar elementos que no interesan
edades = [25, 17, 34, 16, 45, 12, 67]

for edad in edades:
    if edad < 18:
        continue  # Salta menores de edad
    print(f"Paciente adulto: {edad} años")

# En este estamos mirando que edades hay dentro de todas las que no sean menores de 18

 ## Ejercicios: Bucles



 ### Ejercicio 1



 Bucle for básico:



 1. Crea una lista `sintomas = ["fiebre", "tos", "dolor de cabeza", "fatiga"]`

 2. Usa un bucle for para recorrer la lista e imprimir cada síntoma

 3. Modifica el bucle para mostrar: "Síntoma: {nombre_sintoma}"

In [3]:
# Respuesta ejercicio 1
# Bucle for básico:
# 1.- Crea una lista sintomas = ["fiebre", "tos", "dolor de cabeza", "fatiga"]
sintomas = ["fiebre", "tos", "dolor de cabeza", "fatiga"]

# 2.- Usa un bucle for para recorrer la lista e imprimir cada síntoma
for elemento in sintomas:
  print(elemento)

# 3.- Modifica el bucle para mostrar: "Síntoma: {nombre_sintoma}"
for elemento in sintomas:
  print(f"Síntoma: {elemento}")

fiebre
tos
dolor de cabeza
fatiga
Síntoma: fiebre
Síntoma: tos
Síntoma: dolor de cabeza
Síntoma: fatiga


 ### Ejercicio de transición 1.5



 Práctica básica con bucles:



 1. Crea una lista `medicamentos = ["Aspirina", "Paracetamol"]`

 2. Usa un bucle for para mostrar cada medicamento

 3. Añade "Ibuprofeno" a la lista y repite el bucle

In [5]:
# Respuesta ejercicio de transición 1.5

# Práctica básica con bucles:
# 1.- Crea una lista medicamentos = ["Aspirina", "Paracetamol"]
medicamentos = ["Aspirina", "Paracetamol"]

# 2.- Usa un bucle for para mostrar cada medicamento
for elemento in medicamentos:
  print(elemento)

# 3.- Añade "Ibuprofeno" a la lista y repite el bucle
medicamentos.append("ibuprofeno")

for elemento in medicamentos:
  print(elemento)



Aspirina
Paracetamol
Aspirina
Paracetamol
ibuprofeno


 ### Ejercicio 2



 Bucle for con condicionales:



 1. Crea una lista `temperaturas = [36.5, 37.8, 36.9, 38.5, 37.2]`

 2. Recorre la lista con un bucle for

 3. Para cada temperatura, evalúa si es fiebre (>37.5) o normal y guarda el resultado en la variable estado.

 4. Muestra: "Temperatura {valor}°C: {estado}"

In [ ]:
# Respuesta ejercicio 2


 ### Ejercicio 3



 Usando range():



 1. Usa `range(8, 18)` para crear horarios de consulta de 8:00 a 17:00

 2. Muestra cada hora con formato: "Consulta disponible a las {hora}:00"

 3. Modifica para mostrar solo horarios pares usando `range(8, 18, 2)`

In [ ]:
# Respuesta ejercicio 3


 ### Ejercicio de transición 3.5



 Práctica con range básico:



 1. Usa `range(3)` para contar del 0 al 2

 2. En cada iteración muestra: "Paso número: {número}"

 3. Usa `range(1, 4)` para contar del 1 al 3

In [ ]:
# Respuesta ejercicio de transición 3.5


 ### Ejercicio 4



 Enumerate básico:



 1. Crea una lista `pacientes = ["María", "Juan", "Carmen", "Pedro"]`

 3. Crea otra versión que muestre: "Posición {índice}: {nombre}"

In [ ]:
# Respuesta ejercicio 4


 ### Ejercicio 5



 Bucle while básico:



 1. Crea un contador que empiece en 1

 2. Usa while para contar hasta 5

 3. En cada iteración muestra: "Revisando paciente número {contador}"

 4. No olvides incrementar el contador para evitar bucle infinito

In [ ]:
# Respuesta ejercicio 5


 ### Ejercicio de transición 5.5



 While con condición simple:



 1. Crea una variable `pacientes_pendientes = 3`

 2. Mientras haya pacientes pendientes, muestra: "Quedan {número} pacientes"

 3. Reduce en 1 cada vez hasta llegar a 0

In [ ]:
# Respuesta ejercicio de transición 5.5


 ### Ejercicio 6



 Operaciones con bucles:



 1. Crea una lista `pesos = [65.5, 78.2, 45.8, 90.1, 72.0]`

 2. Usa un bucle for para:

    - Sumar todos los pesos (crea una variable suma)

    - Contar cuántos pesos hay

    - Calcular el promedio al final

 3. Muestra el resultado final


 Aviso: Daos cuenta que estas mismas acciones sobre una lista las podemos hacer con las funciones sum(), len() etc. para listas. en este caso lo estamos haciendo manualmente con un bucle for. De hecho es lo que hacen esas funciones internamente.

In [ ]:
# Respuesta ejercicio 6


 ### Ejercicio 7



 Break en acción:



 1. Crea una lista `valores_glucosa = [85, 92, 180, 95, 110]`

 2. Recorre la lista buscando valores peligrosos (>150)

 3. Cuando encuentres uno, muestra "ALERTA: Glucosa {valor} mg/dL" y sal del bucle con break

 4. Si no encuentras ninguno, muestra "Todos los valores normales"

In [ ]:
# Respuesta ejercicio 7


 ### Ejercicio 8



 Continue en acción:



 1. Crea una lista `edades = [25, 16, 34, 12, 45, 17, 67, 15]`

 2. Usa un bucle for para procesar solo pacientes adultos (>=18)

 3. Usa continue para saltar menores de edad

 4. Muestra: "Paciente adulto: {edad} años"

In [ ]:
# Respuesta ejercicio 8


 ### Ejercicio de transición 8.5



 Práctica con continue:



 1. Crea una lista `temperaturas = [36.8, 38.2, 37.0, 39.1]`

 2. Usa continue para saltar temperaturas normales (<37.5)

 3. Solo muestra las temperaturas de fiebre

In [ ]:
# Respuesta ejercicio de transición 8.5


 ### Ejercicio 9



 Bucles anidados:



 1. Crea una lista de listas: `consultas = [["María", "9:00"], ["Juan", "10:00"], ["Carmen", "11:00"]]`

 2. Usa un bucle for para recorrer cada consulta

 3. Dentro, usa otro bucle for para mostrar cada elemento de la consulta

 4. Formato: "Dato: {elemento}"

In [ ]:
# Respuesta ejercicio 9


 ### Ejercicio 11



 Búsqueda y conteo:



 1. Crea una lista `medicamentos = ["Paracetamol", "Ibuprofeno", "Paracetamol", "Aspirina", "Paracetamol"]`

 2. Usa un bucle for para contar cuántas veces aparece "Paracetamol"

 3. Usa otro bucle para encontrar todas las posiciones donde aparece

 4. Muestra ambos resultados


 Aviso: de nuevo, esto se puede hacer también con las funciones .count() y .index() para listas, pero aquí lo estamos haciendo a mano.

In [ ]:
# Respuesta ejercicio 11


 ### Ejercicio 12



 While con validación:



 1. Simula entrada de datos: crea una lista `entradas = [15, 25, -5, 30, 0]`

 2. Usa while con un índice para recorrer la lista

 3. Procesa solo valores positivos

 4. Para el bucle cuando encuentres un 0 o llegues al final

 5. Cuenta cuántos valores válidos procesaste

In [ ]:
# Respuesta ejercicio 12


 ### Ejercicio 13



 Sistema de triaje completo:



 1. Crea listas paralelas:

    - `nombres = ["Ana", "Luis", "Carmen", "Pedro"]`

    - `urgencias = [3, 1, 2, 3]` (1=crítico, 2=urgente, 3=normal)

 2. Usa enumerate() para procesar cada paciente

 3. Usa continue para saltar pacientes normales (urgencia=3)

 4. Para críticos (urgencia=1), muestra "CRÍTICO" y usa break

 5. Para urgentes, solo muestra "Urgente: {nombre}"

In [ ]:
# Respuesta ejercicio 13


## EJERCICIO INTEGRADOR FINAL

### Sistema de Evaluación de Pacientes

Vamos a crear un programa completo que use **todos** los conceptos que has aprendido. Imagina que eres el responsable de organizar la atención en una consulta médica.

#### Paso 1: Preparar los datos
Crea una lista llamada `pacientes` con esta información:

```python
pacientes = [
    ["Ana García", 25, 37.2, ["dolor cabeza"]],
    ["Luis Martín", 67, 38.8, ["tos", "fiebre", "fatiga"]],
    ["Carmen López", 15, 36.9, []],
    ["Pedro Ruiz", 45, 39.2, ["dolor pecho", "mareo", "sudoración", "náuseas"]]
]
```

Cada paciente tiene: nombre (string), edad (int), temperatura (float), síntomas (lista de strings)

#### Paso 2: Analizar cada paciente
Para cada paciente en tu lista, tu programa debe:

1. **Mostrar información básica:**
   - Nombre y edad
   - Temperatura con clasificación: "Normal" (<37.5), "Fiebre" (37.5-39), "Fiebre alta" (>39)
   - Número de síntomas

2. **Determinar el grupo de edad:**
   - "Menor" si edad < 18
   - "Adulto" si edad entre 18-65  
   - "Mayor" si edad > 65

3. **Asignar prioridad de atención:**
   - "URGENTE" si: temperatura > 39 O (es mayor de 65 años Y tiene fiebre)
   - "NORMAL" en el resto de casos

#### Paso 3: Hacer estadísticas simples
Al final, calcula y muestra:
- Cuántos pacientes había en total
- La temperatura promedio (suma todas las temperaturas y divide entre el número de pacientes)
- Cuántos pacientes necesitan atención urgente

#### Paso 4: Lista de urgencias
Crea una nueva lista que contenga solo los nombres de los pacientes urgentes

#### Tu programa debe mostrar algo así:
```
CONSULTA MÉDICA DEL DÍA:

PACIENTE: Ana García (25 años) - Adulto
Temperatura: 37.2°C (Normal)
Síntomas: 1
PRIORIDAD: NORMAL

PACIENTE: Luis Martín (67 años) - Mayor  
Temperatura: 38.8°C (Fiebre)
Síntomas: 3
PRIORIDAD: URGENTE

[continúa con todos los pacientes...]

RESUMEN DEL DÍA:
Total de pacientes: 4
Temperatura promedio: 38.0°C
Pacientes urgentes: 2

Lista de urgencias: Luis Martín, Pedro Ruiz
```

**Conceptos que debes usar y pistas de cómo hacerlo (SOLO LEER SI NO OS ESTÁ SALIENDO LA TAREA):**

- **Variables:** Crea contadores como `total_pacientes`, `suma_temperaturas`, `pacientes_urgentes`
- **Lista de listas:** Usa `pacientes[0][1]` para acceder a la edad del primer paciente, `pacientes[?][2]` para temperaturas
- **Bucle for:** `for paciente in pacientes:` o `for i in range(len(pacientes)):`
- **Acceso a elementos:** `nombre = paciente[0]`, `edad = paciente[1]`, `temp = paciente[2]`, `sintomas = paciente[3]`
- **Condicionales if/elif/else:** Para clasificar temperatura, edad y prioridad
- **Operadores de comparación:** `temp < 37.5`, `edad >= 18 and edad <= 65`
- **Operadores lógicos:** `temp > 39 or (edad > 65 and temp >= 37.5)` para urgencias
- **Función len():** `len(pacientes)` para total, `len(sintomas)` para contar síntomas
- **Función sum():** `sum([temp1, temp2, temp3, temp4])` para sumar temperaturas
- **F-strings:** `f"PACIENTE: {nombre} ({edad} años)"` para mostrar resultados
- **Listas vacías:** `urgentes = []` y después `urgentes.append(nombre)` para pacientes urgentes
- **División:** `promedio = suma_temperaturas / total_pacientes` para calcular promedio